#!/usr/bin/env python3
"""
docker-generator.py — Per-skill Dockerfile generator for dependency-resolver v4.0.0

Reads a skill's manifest.json and generates a Dockerfile with all pre-installed tooling.

Usage:
    python docker-generator.py --skill security-auditor --output ./Dockerfile
    python docker-generator.py --skill load-tester --base-image python:3.11-slim
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Jinja2 is preferred but we provide a minimal fallback string-based templating
# to avoid hard-failing if jinja2 is not yet installed.

try:
    from jinja2 import Template
    HAS_JINJA = True
except ModuleNotFoundError:
    HAS_JINJA = False


def _load_manifest(manifest_path: Path) -> dict[str, Any]:
    with manifest_path.open("rb") as f:
        return json.load(f)


def _fallback_render(template_str: str, context: dict[str, Any]) -> str:
    """Minimal Jinja2-like renderer for basic loops and variables."""
    # Render {{ var }}
    def replace_vars(text: str, ctx: dict[str, Any]) -> str:
        pattern = re.compile(r"\{\{\s*(\w+)\s*\}\}")

        def repl(m):
            key = m.group(1)
            val = ctx.get(key, "")
            if isinstance(val, list):
                return ", ".join(str(v) for v in val)
            return str(val)

        return pattern.sub(repl, text)

    # Render {% for x in y %} ... {% endfor %}
    def replace_loops(text: str, ctx: dict[str, Any]) -> str:
        pattern = re.compile(
            r"\{%\s*for\s+(\w+)\s+in\s+(\w+)\s*%\}(.*?)\{%\s*endfor\s*%\}",
            re.DOTALL,
        )

        def repl(m):
            item_name = m.group(1)
            collection_name = m.group(2)
            body = m.group(3)
            collection = ctx.get(collection_name, [])
            if not isinstance(collection, list):
                return ""
            out = []
            for item in collection:
                sub_ctx = dict(ctx)
                sub_ctx[item_name] = item
                out.append(replace_vars(body, sub_ctx))
            return "".join(out)

        # Apply repeatedly until stable
        prev = None
        while prev != text:
            prev = text
            text = pattern.sub(repl, text)
        return text

    text = template_str
    text = replace_loops(text, context)
    text = replace_vars(text, context)
    return text


def _render_dockerfile(
    skill_name: str,
    manifest: dict[str, Any],
    base_image: str,
    apt_packages: list[str],
    template_path: Path | None = None,
) -> str:
    deps = manifest.get("dependencies", {})
    binaries = deps.get("binaries", [])
    pyproject_extras = deps.get("pyproject_extras", [])

    context = {
        "base_image": base_image,
        "skill_name": skill_name,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "apt_packages": apt_packages,
        "binaries": binaries,
        "pyproject_extras": pyproject_extras,
    }

    if template_path and template_path.exists():
        template_text = template_path.read_text()
    else:
        # Default inline template
        template_text = """# Dockerfile for skill: {{ skill_name }}
# Generated by dependency-resolver v4.0.0 at {{ timestamp }}

FROM {{ base_image }}

LABEL skill="{{ skill_name }}"
LABEL generated_by="dependency-resolver-4.0.0"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \\
    git \\
    curl \\
    ca-certificates \\
{% for pkg in apt_packages %}    {{ pkg }} \\
{% endfor %}    && rm -rf /var/lib/apt/lists/*

{% for binary in binaries %}
{% if binary == "semgrep" %}
RUN npm install -g @semgrep/semgrep
{% elif binary == "k6" %}
RUN curl -sL https://github.com/grafana/k6/releases/download/v0.48.0/k6-v0.48.0-linux-amd64.tar.gz | tar -xz -C /usr/local/bin
{% elif binary == "docker" %}
RUN curl -fsSL https://get.docker.com | sh
{% else %}
# TODO: Add installation instructions for '{{ binary }}'
{% endif %}
{% endfor %}

{% if pyproject_extras %}
COPY pyproject.toml .
RUN pip install --no-cache-dir ".[{{ pyproject_extras | join(',') }}]"
{% else %}
COPY pyproject.toml .
RUN pip install --no-cache-dir .
{% endif %}

COPY skills/{{ skill_name }} /app/skills/{{ skill_name }}
WORKDIR /app
CMD ["python", "-m", "skills.{{ skill_name }}.main"]
"""

    if HAS_JINJA:
        template = Template(template_text)
        return template.render(**context)
    else:
        return _fallback_render(template_text, context)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", required=True, help="Skill name")
    parser.add_argument("--skills-dir", default="/mnt/agents/skills")
    parser.add_argument("--template", type=str, help="Path to Jinja2 Dockerfile template")
    parser.add_argument("--base-image", default="python:3.11-slim")
    parser.add_argument("--apt-package", action="append", default=["git", "curl", "nodejs", "npm"])
    parser.add_argument("--output", "-o", required=True, help="Output Dockerfile path")
    args = parser.parse_args(argv)

    skills_dir = Path(args.skills_dir)
    skill_dir = skills_dir / args.skill
    manifest_path = skill_dir / "manifest.json"

    if not manifest_path.exists():
        print(f"[ERROR] Manifest not found: {manifest_path}", file=sys.stderr)
        return 1

    manifest = _load_manifest(manifest_path)
    template_path = Path(args.template) if args.template else None

    dockerfile = _render_dockerfile(
        skill_name=args.skill,
        manifest=manifest,
        base_image=args.base_image,
        apt_packages=args.apt_package,
        template_path=template_path,
    )

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        f.write(dockerfile)

    print(f"[OK] Dockerfile written to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
